apiVersion: v1
baseDomain: redhat.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: test-cluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.126.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}

publish: External
pullSecret: 
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDs7Zx5xV2DTF0nnJd7uzzHDRh2B6KwN+JF5NrG7kQV8aV2UV0iYZ0CEStDqiAm/x/+Za7W3/9qYeyGASbQe+0sHIufXSj2SJlRUx2wVJOu3JYZGdFODJrfiIjJPbmW20jxKJQl7KiLA5brmWyIyvmYK1RuY/y2eFJ5qk56D8wvoSKY0udRIihjBky5qvyqPlBlcL+C1hwYjvRYmAWLb7pgJlVnAuDgGqI9cvc1PIkqRxjL8Yn5PnzdAYkTl3TK9Ik70gy/n/CyPlNPdC+KBnvQFszOJH1OMVOkIExJ/xandfN2MHOIe01fYWylziN4qvAQcEyw93rLEjrw3y741ntzGMLiPVabGnrEMxpNKkYYAfJfPB6PwHta/31wrFl53HU3Faa4qTDnxSkss3jLtbWKcW9DsCeBJbo81xkpu4hIvJLtAKlj1tH6G9xDYxxANGoZxsZPNT3NGhpNjbRgGbR2SuPT0NTR3NGmpjkt4+RheLpFnZMbMfo2lQWf82XQKq0= eran@localhost.localdomain

