apiVersion: v1
baseDomain: localhost
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: cluster2
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.126.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29tdWxhcjFyZWRoYXRjb20xaml3d285cDF2bXBpYmlwYWlseXJhdzNlamU6RFo3QVdTRDRPTzFRTlcwVDg4T1pWQTlZRlhQNlMyV0VFOEZNMFA0Q0ZOWVZDQTNXUEZRMVhMMFEyMzJETFQ1Ng==","email":"omular@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29tdWxhcjFyZWRoYXRjb20xaml3d285cDF2bXBpYmlwYWlseXJhdzNlamU6RFo3QVdTRDRPTzFRTlcwVDg4T1pWQTlZRlhQNlMyV0VFOEZNMFA0Q0ZOWVZDQTNXUEZRMVhMMFEyMzJETFQ1Ng==","email":"omular@redhat.com"},"registry.connect.redhat.com":{"auth":"NTAwMDkyMTd8dWhjLTFKSXd3bzlwMXZtcEliSXBBSWx5ckFXM0VKRTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhOVGd6TTJGbE5UVmpZalkwWVRoa09UVXdNV0kzTkRjMU56UmpaRGd3T1NKOS5ONVZBNFYwNGZfSGpneGxYd1FSamxpVDdhM25GeGJCOXlWVkxCS043TG5mRy1ncFBFWTJPT1N6V3M5a0EzRHVsdmVLQV93YndsVTJwVWxkQXFGa0FDbEtYUVhFOFo2LWhFTjZTSHVOaVlPWkVab3JnakhacXVEVENUR2p5NjBwWWduWEFnaFplYjBvWTBINC1GaTQyU0tzdmQxa2ZxRHhvSXpPZ0RIekxEdDlKclhBWENUSGFPNjdhT09HNUpaX2M3WHoycGxrakI3MExFM1l1STJTUUxmMXROUWh0QUx5OXZOWlphM2dLOUlQWHJsbjJlRUEzcmlzN1E0enAtZy1IbTR6U2VMbVA2S0tjcXRBUEVnTXNXeUdVSmVpVFJaV2JUMmVEYUFUMDZRME5RbnZPMk84TXBlZ3pBbWNRN2NVWm5Ob0NPV3dtUjk2RWZvUllVaG1OVmVmZmV6SEx6LUx3TmQyVjZ2UW8zSXZzYzhoZnNXazlzdWFVNWpkblE2blk4YnFfZU1vcWlkMFFHMndZU3lyU1hsYnFJTGFhNHp2bnRYdDlESjdZV2xwNnp0XzNPRUtGR256aFoyVThjT2U3V3ZOdEoyemZXcl9Oa0J4RlpkMUlyOGR2R19JVkhYd25aMkxnd080QTQyWmdGcUNZbGx4U2Q5TUZRckNaWmRkekRvdHFoaG5QTnZNaHl2QWdTQVl6NldXWU5XVVZvR1FmM19GeVN6SmFydXhhcW90Mm5ERnFGdXAzUFdPWVlTd0syZUNLTDdaOV9vZVpFdEhNOGZVRXhlUzBrcVYyNVlXR2hjY1gyLTd1SGNUM1JqLV9wMm9DeFBVVS16NGNDUGd0MG1lNUdNS2k4c3ZlVFBLanVjS0hxLWVrcDk3MGh5dWVXbWx6YjctSDE0MA==","email":"omular@redhat.com"},"registry.redhat.io":{"auth":"NTAwMDkyMTd8dWhjLTFKSXd3bzlwMXZtcEliSXBBSWx5ckFXM0VKRTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhOVGd6TTJGbE5UVmpZalkwWVRoa09UVXdNV0kzTkRjMU56UmpaRGd3T1NKOS5ONVZBNFYwNGZfSGpneGxYd1FSamxpVDdhM25GeGJCOXlWVkxCS043TG5mRy1ncFBFWTJPT1N6V3M5a0EzRHVsdmVLQV93YndsVTJwVWxkQXFGa0FDbEtYUVhFOFo2LWhFTjZTSHVOaVlPWkVab3JnakhacXVEVENUR2p5NjBwWWduWEFnaFplYjBvWTBINC1GaTQyU0tzdmQxa2ZxRHhvSXpPZ0RIekxEdDlKclhBWENUSGFPNjdhT09HNUpaX2M3WHoycGxrakI3MExFM1l1STJTUUxmMXROUWh0QUx5OXZOWlphM2dLOUlQWHJsbjJlRUEzcmlzN1E0enAtZy1IbTR6U2VMbVA2S0tjcXRBUEVnTXNXeUdVSmVpVFJaV2JUMmVEYUFUMDZRME5RbnZPMk84TXBlZ3pBbWNRN2NVWm5Ob0NPV3dtUjk2RWZvUllVaG1OVmVmZmV6SEx6LUx3TmQyVjZ2UW8zSXZzYzhoZnNXazlzdWFVNWpkblE2blk4YnFfZU1vcWlkMFFHMndZU3lyU1hsYnFJTGFhNHp2bnRYdDlESjdZV2xwNnp0XzNPRUtGR256aFoyVThjT2U3V3ZOdEoyemZXcl9Oa0J4RlpkMUlyOGR2R19JVkhYd25aMkxnd080QTQyWmdGcUNZbGx4U2Q5TUZRckNaWmRkekRvdHFoaG5QTnZNaHl2QWdTQVl6NldXWU5XVVZvR1FmM19GeVN6SmFydXhhcW90Mm5ERnFGdXAzUFdPWVlTd0syZUNLTDdaOV9vZVpFdEhNOGZVRXhlUzBrcVYyNVlXR2hjY1gyLTd1SGNUM1JqLV9wMm9DeFBVVS16NGNDUGd0MG1lNUdNS2k4c3ZlVFBLanVjS0hxLWVrcDk3MGh5dWVXbWx6YjctSDE0MA==","email":"omular@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCYS7zlpRBN0X6mbuzihk9YD/A0tnb+y1B/YXUvh+ekTw5fczYSpGPsgEfsWFHvMOqK1S3bvFdEnN7blAxEj1QeHMKVLIDPjOJdLYRx+4otX11W1zI8mP2iOn+GvWGyEQqKNk5lrLMqPh68RyGu0xoKlINTOCdHVw0srwbRsVRCc/Q7xUlspQMNozTn8yIDhkvv6LL2Fe67SmFFE7U23VYQr4MY3Xh4EpV6gO5xxPchYh+vP5/Yhuf1MMtMpslBfO3rypTdHdOagUmTxu74l2S2uo97pt4VbGFgX8eZB2dZtbSaerAcXiluiwGq/jeTFMdlSJM6GZeG3GCTQgPmqWPbE8JZmSWJf6PAZx9sUFYtXN4MwKPsSWd7LnWhsadH4AudkjV2xZYkM5md/+pMDibYX/Y/LQpIoMUnsYmIcjgc2T7pM25vabxN1Wv1+/WyylGiqhocEWXglnsvbXsVG3Clw089xU+r+CPBTeFXQQdQQAWQPpGdLp4S1obedi6kFx0= root@dell-730-060.dsal.lab.eng.rdu2.redhat.com
